# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings
title: SRVD
description: SRVD is building the Veteran community infrastructure built on trust. We are ONE because we have SRVD.

# Build settings
markdown: kramdown

# SASS
sass:
    style: compressed
